---
parsing-setup:
  metrics:
    method: "default"
    args: {}
  logfile:
    method: "default"
    args: {}
  artifacts:
    method: "default"
    args: {}

run-setup:
  group-by: "auto"
  num-runs-limit: 25
  num-runs-start: 0
  parallel: 1

seed: 1
